### ISSUE TITLE
API Documentation Website Issue

### ISSUE THREAD

**Issue by htcrane** [Microchip-MPLAB-Harmony/wireless_ble#1]
The documentation build failed so the Github pages for this repo did not publish. See [https://microchip-mplab-harmony.github.io/wireless_ble](https://microchip-mplab-harmony.github.io/wireless_ble) does not work. @MPLABHarmony

**Comment by aethaniel** [comment]
Thanks for reporting!
This issue will be solved with next coming release. We found the issue in the documentation rendering here.
Meanwhile, you can see it in better way from the cloned repository in your computer.
